<?php

namespace AppBundle\Repository;

/**
 * ResaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResaRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTicket($rawVisite)
    {
         $jVisite = $rawVisite->format('Y-m-d');
         $query = $this->_em->createQuery(
            'SELECT COUNT(r.jour_visite)
            FROM AppBundle:Resa r
            WHERE r.jour_visite = :jvisite'
            )->setParameter('jvisite', $jVisite);

        $nTickets = $query->setMaxResults(1)->getOneOrNullResult();;
        $nTickets = intval($nTickets[1]);

        if ($nTickets > 1000) {
             return true;
        } else {
            return false;
        }
    }
}