# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.mailer:
       class: AppBundle\Services\Mailer
       arguments: ["@mailer","@twig"]
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    app.persistresa :
        class: AppBundle\Services\PersistResa
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@router"]
    app.stripe_manager:
       class: AppBundle\Services\StripeManager
       arguments: ["@session","@router","@app.persistresa"]